#\\\\\\\\\\\\\\\\\\\#
#\\\\\\ALIASES\\\\\\#
#\\\\\\\\\\\\\\\\\\\#
alias ls='ls --color=auto'
alias clear='TERMINFO=/usr/share/terminfo TERM=xterm /usr/bin/clear'
alias dt='cd ~/.config'
alias dush='sudo du -h --max-depth=1'
alias hex='hyprctl dispatch exit'
alias hre='hyprctl reload'
alias lS='ls -ShAlF'
alias lx='ls -XhAlFr'
alias lr='ls -hAlFR'
alias lt='ls -thAlF'
alias ltr='ls -thAlFr'
alias ll='ls -hAlF'
alias la='ls -Ah'
alias l='ls -CFh'
alias na='nano $CFB/.balias.sh'
alias nb='nano $CFB/.bashrc'
alias ns='nano $HOME/code/sandbox/log.md'
alias nn='nano $CF/nano/nanorc'
alias ts='date "+%y%m%d_%H%M%S"'
alias vs='code tunnel --disable-telemetry'
